#!/bin/sh
# written by Shotaro Fujimoto (https://github.com/ssh0)
# 
# Remove the symbolic link in the config file (default: ./setup_config_link).
# After execute this script, you should run setup.sh in the dotfiles directory.

configfile="./setup_config_link"

usage() {
  echo "Remove the symbolic link in the config file (default: $configfile)."
  echo "After execute this script, you should run setup.sh in the dotfiles directory.\n"
  echo "Usage: dotclean [OPTION]\n"
  echo "OPTION:"
  echo "  -h: Show this message."
  exit 1
}

if [ "$1" = "-h" ]; then
  usage
fi

for l in $(grep -Ev '^#' "${configfile}" | grep -Ev '^$'); do
  orig="$HOME/$(echo "$l" | awk 'BEGIN {FS=","; }  { print $2; }')"
  if [ -L "${orig}" ]; then
    echo "rm ${orig}@"
    rm ${orig}
  fi
done
