#!/bin/bash
###############################################################################
#       _               _         _   _        __ _                           #
#      | |__   ___ _ __| |__  ___| |_| |_   _ / _| |_ _      _ _ __ ___       #
#      | '_ \ / _ \ '__| '_ \/ __| __| | | | | |_| __| \ /\ / | '_ ` _ \      #
#      | | | |  __/ |  | |_) \__ \ |_| | |_| |  _| |_ \ V  V /| | | | | |     #
#      |_| |_|\___|_|  |_.__/|___/\__|_|\__,_|_|  \__| \_/\_/ |_| |_| |_|     #
#                                                                             #
###############################################################################
# Initialise                                                                {{{
#------------------------------------------------------------------------------

hc() {
    herbstclient "$@"
}

# use example script from:
src='/usr/share/doc/herbstluftwm/examples/'

hc emit_hook reload

if hc new_attr bool my_not_first_autostart 2> /dev/null; then
    gnome-settings-daemon &
    xscreensaver -no-splash &
    dropbox start
    compton -b --config $HOME/.config/compton/compton.conf
fi

if hash nitrogen 2>&1 1>/dev/null; then
  nitrogen --restore
elif [ -f $HOME/.fehbg ]; then
  hc spawn $HOME/.fehbg
fi

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors 1

source ~/.config/herbstluftwm/pad.sh
split_rate_h=${split_rate_h:-0.5}
resizestep_h=${resizestep_h:-0.005}
split_rate_v=${split_rate_v:-0.5}
resizestep_v=${resizestep_v:-0.02}

hc set tree_style '╾│ ├└╼─┐'

#---------------------------------------------------------------------------}}}
# Keybindings                                                               {{{
#------------------------------------------------------------------------------

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-c       close_or_remove
hc keybind $Mod-Shift-c remove
hc keybind $Mod-Return  spawn urxvt

# basic movement
# focusing clients
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-h focus left
hc keybind $Mod-l focus right
# cycle
hc keybind $Mod-Down cycle_all +1
hc keybind $Mod-Up   cycle_all -1

# moving clients
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-l shift right

# resizing frames
hc keybind $Mod-z      resize down  +$resizestep_v
hc keybind $Mod-a      resize up    +$resizestep_v
hc keybind $Mod-comma  resize left  +$resizestep_h
hc keybind $Mod-period resize right +$resizestep_h

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-s chain , split bottom $split_rate_h , focus down
hc keybind $Mod-v chain , split right  $split_rate_v , focus right
hc keybind $Mod-Control-j chain , split bottom 0.5 , focus down
hc keybind $Mod-Control-k chain , split top    0.5 , focus up
hc keybind $Mod-Control-h chain , split left   0.5 , focus left
hc keybind $Mod-Control-l chain , split right  0.5 , focus right
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible
# shift client to neighbor tag
hc keybind $Mod-Shift-Right move_index +1 --skip-visible
hc keybind $Mod-Shift-Left  move_index -1 --skip-visible

# layouting
# in tag
hc keybind $Mod-t         floating toggle
hc keybind $Mod-Shift-t   spawn ~/.config/herbstluftwm/toggle_single_float.sh
hc keybind $Mod-Control-f spawn ~/.config/herbstluftwm/maximize.sh
hc keybind $Mod-Shift-f   fullscreen toggle
# in flame
hc keybind $Mod-space   cycle_layout 1
hc keybind $Mod-f       cycle_layout 1 max vertical
# for window
hc keybind $Mod-o       pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# switch focus to different monitor
hc keybind $Mod-Tab         cycle_monitor +1
hc keybind $Mod-Shift-Tab   cycle_monitor -1

# reload dzen2
hc keybind $Mod-F11 spawn ~/.config/herbstluftwm/reload_panel.sh
# dmenu_run
hc keybind $Mod-p spawn dmenu_run -l 10 -fn "Migu 1M:size=20"
# toggle compton
hc keybind Alt-Control-t spawn bash toggle_compton.sh
# lock screen
hc keybind Alt-Control-l spawn xscreensaver-command -lock
# Launch file manager
hc keybind $Mod-e spawn thunar
# Play / Pause media key
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86HomePage  spawn mpc toggle
hc keybind Shift-F6      spawn mpc toggle
hc keybind Shift-XF86AudioPlay spawn streamradio pause
hc keybind Shift-XF86HomePage  spawn streamradio pause
# Volume setting media key
hc keybind XF86AudioRaiseVolume spawn sound_volume_change_wrapper.sh +
hc keybind XF86AudioLowerVolume spawn sound_volume_change_wrapper.sh -
hc keybind XF86AudioMute        spawn sound_volume_change_wrapper.sh m
# Brightness
hc keybind XF86MonBrightnessUp   spawn xbacklight + 5 -time 100 -steps 1
hc keybind XF86MonBrightnessDown spawn xbacklight - 5 -time 100 -steps 1
# Take a screenshot (whole window)
hc keybind Print spawn screenshot.sh
# Take a screenshot (selected area)
hc keybind Shift-Print spawn screenshot_select.sh
# Toggle touchpad
hc keybind Control-Escape spawn touchpad_toggle.sh
# Toggle trackpoint (Lenovo PC)
hc keybind Alt-Escape spawn trackpoint_toggle.sh

# herbstcommander
hc keybind $Mod-colon spawn ${src}herbstcommander.sh
# Focus specified client by name (using dmenu)
hc keybind $Mod-g spawn ${src}herbstcommander.sh jumpto
# Bring specified client by name (using dmenu)
hc keybind $Mod-b spawn ${src}herbstcommander.sh bring
# Open q3-like terminal for arbitrary application
hc keybind $Mod-bracketright chain . spawn ${src}q3terminal.sh . emit_hook focus_changed

#---------------------------------------------------------------------------}}}
# Appearance                                                                {{{
#------------------------------------------------------------------------------

hc set frame_gap 8
hc set frame_padding -12
hc set frame_border_width 2
hc set frame_transparent_width 0
hc set window_gap 12
hc set window_border_width 2
hc set window_border_inner_width 0

# frame options
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# colors
hc set frame_border_active_color  '#ff005f'
hc set frame_border_normal_color  '#262626'
hc set frame_bg_active_color      '#ff005f'
hc set frame_bg_normal_color      '#262626'
hc set window_border_active_color '#ff005f'
hc set window_border_normal_color '#262626'

# opacities (%)
hc set frame_active_opacity 40
hc set frame_normal_opacity 40

hc set pseudotile_center_threshold 14
hc set focus_follows_mouse 1

hc set snap_distance 14
hc set snap_gap 9

hc set default_frame_layout 3

#---------------------------------------------------------------------------}}}
# Rules                                                                     {{{
#------------------------------------------------------------------------------

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class='XClock' pseudotile=on
hc rule class='Conky' manage=off
hc rule class='Screenkey' manage=off
hc rule title='Figure 1' monitor=1

#---------------------------------------------------------------------------}}}
# Panel                                                                     {{{
#------------------------------------------------------------------------------

hc spawn ~/.config/herbstluftwm/reload_panel.sh

#---------------------------------------------------------------------------}}}
hc unlock
