#!/bin/bash
###############################################################################
#       _               _         _   _        __ _                           #
#      | |__   ___ _ __| |__  ___| |_| |_   _ / _| |_ _      _ _ __ ___       #
#      | '_ \ / _ \ '__| '_ \/ __| __| | | | | |_| __| \ /\ / | '_ ` _ \      #
#      | | | |  __/ |  | |_) \__ \ |_| | |_| |  _| |_ \ V  V /| | | | | |     #
#      |_| |_|\___|_|  |_.__/|___/\__|_|\__,_|_|  \__| \_/\_/ |_| |_| |_|     #
#                                                                             #
###############################################################################
# Initialise                                                                {{{
#------------------------------------------------------------------------------

hc() {
    herbstclient "$@"
}

hc emit_hook reload

if hc silent new_attr bool my_not_first_autostart ; then
    gnome-settings-daemon &
    xscreensaver -no-splash &
    compton -b --config $HOME/.config/compton/compton.conf
    [ -f $HOME/.fehbg ] && $HOME/.fehbg
fi

pad_up=28
pad_right=34
pad_down=0
pad_left=33

# 1 - ((31*19 + 16) / (54*19 + 16))
split_rate_h=0.41938579654510555
# 19 / (54 * 19 + 16)
resizestep_v=0.018234165067178502

split_rate_v=0.5467289719626168
resizestep_h=0.004904632152588556

hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors 1

#---------------------------------------------------------------------------}}}
# Keybindings                                                               {{{
#------------------------------------------------------------------------------

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-c       close_or_remove
hc keybind $Mod-Shift-c remove
hc keybind $Mod-Return  spawn urxvt

# basic movement
# focusing clients
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-h focus left
hc keybind $Mod-l focus right
# cycle
hc keybind $Mod-Down cycle_all +1
hc keybind $Mod-Up   cycle_all -1

# moving clients
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-l shift right

# resizing frames
hc keybind $Mod-Control-j resize down  +$resizestep_v
hc keybind $Mod-Control-k resize up    +$resizestep_v
hc keybind $Mod-Control-h resize left  +$resizestep_h
hc keybind $Mod-Control-l resize right +$resizestep_h

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-s split bottom $split_rate_h
hc keybind $Mod-v split right  $split_rate_v
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible
# shift client to neighbor tag
hc keybind $Mod-Shift-Right move_index +1 --skip-visible
hc keybind $Mod-Shift-Left  move_index -1 --skip-visible

# layouting
# in tag
hc keybind $Mod-t       floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
# in flame
hc keybind $Mod-space   cycle_layout 1
hc keybind $Mod-f       cycle_layout 1 max vertical
# for window
hc keybind $Mod-o       pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# switch focus to different monitor
hc keybind $Mod-Tab         cycle_monitor +1
hc keybind $Mod-Shift-Tab   cycle_monitor -1

# reload dzen2
hc keybind $Mod-F11 spawn ~/.config/herbstluftwm/reload_panel.sh
# dmenu_run
hc keybind $Mod-p spawn dmenu_run -l 10 -fn "Migu 1M:size=20"
# toggle compton
hc keybind Alt-Control-t spawn bash toggle_compton.sh
# lock screen
hc keybind Alt-Control-l spawn xscreensaver-command -lock
# Launch file manager
hc keybind $Mod-e spawn thunar
# Play / Pause media key
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86HomePage  spawn mpc toggle
hc keybind Shift-F6      spawn mpc toggle
hc keybind Shift-XF86AudioPlay spawn streamradio pause
hc keybind Shift-XF86HomePage  spawn streamradio pause
# Volume setting media key
hc keybind XF86AudioRaiseVolume spawn sound_volume_change_wrapper.sh +
hc keybind XF86AudioLowerVolume spawn sound_volume_change_wrapper.sh -
hc keybind XF86AudioMute        spawn sound_volume_change_wrapper.sh m
# Brightness
hc keybind XF86MonBrightnessUp   spawn xbacklight + 5 -time 100 -steps 1
hc keybind XF86MonBrightnessDown spawn xbacklight - 5 -time 100 -steps 1
# Take a screenshot (whole window)
hc keybind Print spawn screenshot.sh
# Take a screenshot (selected area)
hc keybind Shift-Print spawn screenshot_select.sh
# Toggle touchpad
hc keybind Control-Escape spawn touchpad_toggle.sh
# Toggle trackpoint (Lenovo PC)
hc keybind Alt-Escape spawn trackpoint_toggle.sh

# Focus specified client by name (using dmenu)
hc keybind $Mod-g spawn ~/.config/herbstluftwm/focus_client_by_name.sh
# Bring specified client by name (using dmenu)
hc keybind $Mod-b spawn ~/.config/herbstluftwm/bring_client_by_name.sh

#---------------------------------------------------------------------------}}}
# Appearance                                                                {{{
#------------------------------------------------------------------------------

#  pad MONITOR [PADUP [PADRIGHT [PADDOWN [PADLEFT]]]]
hc pad 0 $pad_up $pad_right $pad_down $pad_left

hc set frame_gap 8
hc set frame_padding -12
hc set frame_border_width 1
hc set frame_transparent_width 0
hc set window_gap 14
hc set window_border_width 1
hc set window_border_inner_width 0

# frame options
hc set always_show_frame 0
hc set frame_bg_transparent 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# colors
hc set frame_border_active_color  '#8a2c4f'
hc set frame_border_normal_color  '#262626'
hc set frame_bg_active_color      '#8a2c4f'
hc set frame_bg_normal_color      '#262626'
hc set window_border_active_color '#ff005f'
hc set window_border_normal_color '#262626'

# opacities (%)
hc set frame_active_opacity 30
hc set frame_normal_opacity 10

hc set pseudotile_center_threshold 4
hc set focus_follows_mouse 1

#---------------------------------------------------------------------------}}}
# Rules                                                                     {{{
#------------------------------------------------------------------------------

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

#---------------------------------------------------------------------------}}}
# Panel                                                                     {{{
#------------------------------------------------------------------------------

hc spawn ~/.config/herbstluftwm/reload_panel.sh

#---------------------------------------------------------------------------}}}
hc unlock
